# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches:
      - testing
      - main
  pull_request:
    branches:
      - main
jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build -- --prod
      - name: Update webdriver
        run: node node_modules/protractor/bin/webdriver-manager update
      - name: E2E
        run: npm run e2e -- --configuration=ci
